CREATE TABLE MANUFACTURER(
    MANUFACTURER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT'厂商编号',
    INTRODUCTION TEXT COMMENT'简介',
    ACCOUNT_NUMBER VARCHAR(15)UNIQUE NOT NULL COMMENT'账号',
    PASSWORD VARCHAR(15) NOT NULL DEFAULT('123456') COMMENT'密码'
)COMMENT'厂商表';

CREATE TABLE GAME(
    GAME_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT'游戏编号',
    GAME_NAME CHAR(10) NOT NULL COMMENT'游戏名' ,
    MANUFACTURER_ID INT NOT NULL COMMENT'厂商编号',
    INTRODUCTION TEXT COMMENT'游戏简介',
    PRICE DOUBLE NOT NULL DEFAULT(1) COMMENT'售价',
    PUBLISH_TIME DATETIME NOT NULL DEFAULT('1979-10-01 12:00:00') COMMENT'发布日期',
    FOREIGN KEY(MANUFACTURER_ID) REFERENCES MANUFACTURER(MANUFACTURER_ID) ON DELETE CASCADE ON UPDATE CASCADE
)COMMENT'游戏表';

CREATE TABLE USER(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT'用户编号',
    ACCOUNT_NUMBER VARCHAR(15)UNIQUE NOT NULL COMMENT'账号',
    PASSWORD VARCHAR(15) NOT NULL DEFAULT('123456') COMMENT'密码'
)COMMENT'用户表';

CREATE TABLE HAVING_GAMES(
    USER_ID INT NOT NULL COMMENT'用户编号',
    GAME_ID INT NOT NULL COMMENT'游戏编号',
    BUY_TIME DATETIME NOT NULL DEFAULT('1979-10-01 12:00:00') COMMENT'购买日期',
    PLAY_TIME REAL NOT NULL DEFAULT(0) COMMENT'游戏时长',
    PRIMARY KEY(USER_ID,GAME_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(GAME_ID) REFERENCES GAME(GAME_ID) ON DELETE CASCADE ON UPDATE CASCADE
)COMMENT'拥有的游戏表';

CREATE TABLE FRIEND(
    FRIEND_ID INT NOT NULL COMMENT'好友的编号',
    USER_ID INT NOT NULL COMMENT'用户的编号',
    STATE INT COMMENT'状态,0未通过,1已通过',
    PRIMARY KEY(FRIEND_ID,USER_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
)COMMENT'好友表';

CREATE TABLE CONCERN(
    USER_ID INT COMMENT'用户的编号',
    MANUFACTURER_ID INT COMMENT'厂商的编号',
    PRIMARY KEY(USER_ID,MANUFACTURER_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(MANUFACTURER_ID) REFERENCES MANUFACTURER(MANUFACTURER_ID) ON DELETE CASCADE ON UPDATE CASCADE
)COMMENT'关注表';

CREATE TABLE ORDER_FOR_GOODS(
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT'订单编号',
    USER_ID INT NOT NULL COMMENT'用户的编号',
    ORDER_STATE BOOLEAN COMMENT'0未完成,1完成' NOT NULL DEFAULT(0),
    ORDER_TIME DATETIME NOT NULL DEFAULT('1979-10-01 12:00:00'),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
)COMMENT'订单表';

CREATE TABLE ORDER_DETAILS(
    ORDER_ID INT NOT NULL COMMENT'订单编号',
    GAME_ID INT NOT NULL COMMENT'游戏编号',
    DETAIL_TIME DATETIME NOT NULL DEFAULT('1979-10-01 12:00:00'),
    BUY_OR_REFUND INT COMMENT'购买或者退款,0退款,1待购买,3已购买' NOT NULL DEFAULT(1),
    PRIMARY KEY(ORDER_ID,GAME_ID),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDER_FOR_GOODS(ORDER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(GAME_ID) REFERENCES GAME(GAME_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EVALUATETABLE(
    EVALUATE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT'评价编号',
    USER_ID INT NOT NULL COMMENT'用户编号',
    GAME_ID INT NOT NULL COMMENT'游戏编号',
    EVALUATE TEXT COMMENT'评价',
    EVALUATE_DATE DATETIME NOT NULL DEFAULT('1979-10-01 12:00:00') COMMENT'发布日期',
    SCORE REAL NOT NULL DEFAULT(5) COMMENT'评分',
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(GAME_ID) REFERENCES GAME(GAME_ID) ON DELETE CASCADE ON UPDATE CASCADE
)COMMENT'评价表';


CREATE TABLE GAME_TO_TYPE(
    GAME_ID INT  NOT NULL COMMENT'游戏编号',
    TYPE_NAME CHAR(10) NOT NULL COMMENT'类型名',
    PRIMARY KEY(GAME_ID,TYPE_NAME),
    FOREIGN KEY(GAME_ID) REFERENCES GAME(GAME_ID) ON DELETE CASCADE ON UPDATE CASCADE
);