
CREATE VIEW USER_VIEW AS SELECT USER_ID,ACCOUNT_NUMBER,PASSWORD FROM USER;

CREATE VIEW MANUFACTURER_VIEW AS SELECT MANUFACTURER_ID, INTRODUCTION, ACCOUNT_NUMBER, PASSWORD FROM MANUFACTURER;

CREATE VIEW GAME_VIEW AS SELECT GAME_ID,GAME_NAME,GAME.MANUFACTURER_ID,MANUFACTURER.ACCOUNT_NUMBER,GAME.INTRODUCTION,PRICE,PUBLISH_TIME 
FROM GAME,MANUFACTURER WHERE GAME.MANUFACTURER_ID=MANUFACTURER.MANUFACTURER_ID;

CREATE VIEW ORDER_VIEW AS SELECT ORDER_FOR_GOODS.ORDER_ID,USER_ID,GAME_ID,ORDER_STATE,ORDER_TIME 
FROM ORDER_FOR_GOODS,ORDER_DETAILS
WHERE ORDER_FOR_GOODS.ORDER_ID=ORDER_DETAILS.ORDER_ID;

CREATE VIEW CONCER_VIEW AS SELECT USER_ID,MANUFACTURER_ID FROM CONCERN;

CREATE VIEW EVALUATE_VIEW AS SELECT EVALUATE_ID,EVALUATE,USER_ID,GAME_ID,EVALUATE_DATE,SCORE
FROM EVALUATETABLE;